### ISSUE TITLE
error: xdg-mime: not found

### ISSUE THREAD

**Issue by steve21124** [hoodiehq-archive/legacy-hoodie-vagrant#1]
just found out the official repository is here. So I posted in this repository  instead of on the other one
https://github.com/cainvommars/hoodie-vagrant/issues/1#issuecomment-52147089

Version: 0.6.0 (node v0.10.30, npm 1.5.0-alpha-4, platform: linux)

Initializing...
Using remote CouchDB: http://localhost:5985
Waiting for CouchDB [-*----] SUCCESS 
WWW: http://127.0.0.1:6001
Admin: http://127.0.0.1:6002
WARNING: using legacy changes feed pooling (couchdb < 1.4)
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'
All plugins started.

[hoodie] Command failed: /usr/lib/node_modules/hoodie-cli/node_modules/open/vendor/xdg-open: 1: /usr/lib/node_modules/hoodie-cli/node_modules/open/vendor/xdg-open: xdg-mime: not found
xdg-open: no method available for opening 'http://127.0.0.1:6001'

**Comment by ptrwllrt** [comment]
@steve21124 Thanks for the ticket (in both repos ;-))

I'll look into this when I'm back on solid internet.

**Comment by ptrwllrt** [comment]
interesting on a fresh checkout with the latest vagrant i get the following:

Version: 0.6.0 (node v0.10.31, npm 1.5.0-alpha-4, platform: linux)

Initializing...
CouchDB started: http://127.0.0.1:6003
Waiting for CouchDB [----*-] FAILED 

ERR! Error: Timed out waiting for CouchDB. These logs may help:
ERR!    /opt/project/myappname/data/couch.stderr
ERR!    /opt/project/myappname/data/couch.stdout
ERR!    /opt/project/myappname/data/couch.log
ERR!     at Request._callback (/opt/project/myappname/node_modules/hoodie-server/lib/couchdb/index.js:145:27)
ERR!     at self.callback (/opt/project/myappname/node_modules/hoodie-server/node_modules/request/request.js:123:22)
ERR!     at Request.emit (events.js:95:17)
ERR!     at ClientRequest.self.clientErrorHandler (/opt/project/myappname/node_modules/hoodie-server/node_modules/request/request.js:244:10)
ERR!     at ClientRequest.emit (events.js:95:17)
ERR!     at Socket.socketErrorListener (http.js:1547:9)
ERR!     at Socket.emit (events.js:95:17)
ERR!     at net.js:440:14
ERR!     at process._tickDomainCallback (node.js:463:13)

Stopping CouchDB...

**Comment by steve21124** [comment]
you need to set the environment
export COUCH_URL=http://localhost:5985 
export HOODIE_ADMIN_USER=admin 
export HOODIE_ADMIN_PASS=mysecretpassword

export HOODIE_BIND_ADDRESS=0.0.0.0

**Comment by vegardx** [comment]
Did you ever manage to take a look at the original issue? I've tried starting hoodie with `no-open-browser` (which is hardly even documented), but it still tries to start the browser. Normally this wouldn't be an issue, but in hoodie not opening a link is a hard failure, resulting in hoodie terminating.

**Comment by ronycohen** [comment]
I encounter the same issue : 

Initializing...
CouchDB started: http://127.0.0.1:6003
Waiting for CouchDB [-----*] SUCCESS
prompt: Please set an admin password :
WWW:    http://127.0.0.1:6001
Admin:  http://127.0.0.1:6002
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'
All plugins started.

[hoodie] Command failed: /usr/lib/node_modules/hoodie-cli/node_modules/open/vendor/xdg-open: 1: /usr/lib/node_modules/hoodie-cli/node_modules/open/vendor/xdg-open: xdg-mime: not found
xdg-open: no method available for opening 'http://127.0.0.1:6001'

**Comment by janl** [comment]
this has been fixed in https://github.com/hoodiehq/hoodie-cli/commit/5b343c72d437e01bd7db0fde923400a123945000

@boennemann is this in a release yet?

**Comment by ptrwllrt** [comment]
when I freshly boot up the vagrant machine it seems like chouchdb is just not starting -> https://gist.github.com/cainvommars/47c8e12896216f754051

not entirely sure why

(is probably a different issue, but i don't even get to this right now..)

**Comment by janl** [comment]
@cainvommars it’s a different issue, this looks like the ini file(s) can’t be read

**Comment by ronycohen** [comment]
a hoodie start -n solved the pb.
